package yasdb

import (
	"fmt"
	"os"
	"reflect"
	"testing"
)

func TestParseDsn(t *testing.T) {

	os.Mkdir(_DataPath, 0o755)

	dsnTests := []struct {
		dsnStr      string
		expectedDSN *DataSourceName
	}{
		{"sysyasdb_123@127.0.0.1:1688", nil},
		{"sys/yasdb_123127.0.0.1:1688", nil},
		{`/a/b/c?autocommit=true`, nil},
		{
			`sys/yasdb_123@[::ffff:127.0.0.1]:1688?autocommit=true`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "[::ffff:127.0.0.1]:1688",
				IsAutoCommit:      true,
				DataPath:          "",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys/yasdb_123@127.0.0.1:1688?Autocommit=TRUE`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      true,
				DataPath:          "",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys/yasdb\@_123@127.0.0.1:1688?autocommit=true`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb@_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      true,
				DataPath:          "",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys\//yasdb\@_123@127.0.0.1:1688?autocommit=true`,
			&DataSourceName{
				User:              "sys/",
				Password:          "yasdb@_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      true,
				DataPath:          "",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/yasdb_123@127.0.0.1:1688",
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      false,
				DataPath:          "",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys\/\\/yasdb_123@127.0.0.1:1688?autocommit=true`,
			&DataSourceName{
				User:              `sys/\`,
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      true,
				DataPath:          "",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`./test?autocommit=true`,
			&DataSourceName{
				User:              "sys",
				Password:          "",
				Url:               "",
				IsAutoCommit:      true,
				DataPath:          _DataPath,
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`./test`,
			&DataSourceName{
				User:              "sys",
				Password:          "",
				Url:               "",
				IsAutoCommit:      false,
				DataPath:          _DataPath,
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys/yasdb_123@[::1]:1688?autocommit=true`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "[::1]:1688",
				IsAutoCommit:      true,
				DataPath:          "",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys/yasdb_123@[fe80::8535:da9e:9517:1775]:7000?autocommit=true`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "[fe80::8535:da9e:9517:1775]:7000",
				IsAutoCommit:      true,
				DataPath:          "",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys/yasdb_123@[fe80::d5a0:6043:483c:4bfd%ens192]:1688?autocommit=true`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "[fe80::d5a0:6043:483c:4bfd%ens192]:1688",
				IsAutoCommit:      true,
				DataPath:          "",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/Cod-2022@primary:192.168.6.177:2300,192.168.6.177:2302,192.168.6.177:2304",
			&DataSourceName{
				User:              "sys",
				Password:          "Cod-2022",
				Url:               "primary:192.168.6.177:2300,192.168.6.177:2302,192.168.6.177:2304",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/Cod-2022@192.168.6.177:2300,192.168.6.177:2302,192.168.6.177:2304",
			&DataSourceName{
				User:              "sys",
				Password:          "Cod-2022",
				Url:               "192.168.6.177:2300,192.168.6.177:2302,192.168.6.177:2304",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys/yasdb_123@127.0.0.1:1688?ukey_name=dba&ukey_pin=Cod-2022`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688?ukey_name=dba&ukey_pin=Cod-2022",
				IsAutoCommit:      false,
				DataPath:          "",
				ukeyName:          "dba",
				ukeyPin:           "Cod-2022",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys/yasdb_123@127.0.0.1:1688?ukey_name=1&ukey_pin=123&autocommit=true`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688?ukey_name=1&ukey_pin=123",
				IsAutoCommit:      true,
				DataPath:          "",
				ukeyName:          "1",
				ukeyPin:           "123",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys/yasdb_123@127.0.0.1:1688?ukey_name=1`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688?ukey_name=1",
				IsAutoCommit:      false,
				DataPath:          "",
				ukeyName:          "1",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			`sys/yasdb_123@127.0.0.1:1688?ukey_pin=123`,
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688?ukey_pin=123",
				IsAutoCommit:      false,
				DataPath:          "",
				ukeyPin:           "123",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/Cod-2022@LOADBALANCE:192.168.6.177:2300,192.168.6.177:2302,192.168.6.177:2304",
			&DataSourceName{
				User:              "sys",
				Password:          "Cod-2022",
				Url:               "LOADBALANCE:192.168.6.177:2300,192.168.6.177:2302,192.168.6.177:2304",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/Cod-2022@loadbalance:192.168.6.177:2300,192.168.6.177:2302,192.168.6.177:2304",
			&DataSourceName{
				User:              "sys",
				Password:          "Cod-2022",
				Url:               "loadbalance:192.168.6.177:2300,192.168.6.177:2302,192.168.6.177:2304",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/yasdb_123@127.0.0.1:1688?heartbeat_enable=true",
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      false,
				heartbeatEnable:   true,
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/yasdb_123@127.0.0.1:1688?compat_vector=yashan",
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      false,
				compatVector:      "yashan",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/yasdb_123@127.0.0.1:1688?compat_vector=yashan",
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      false,
				compatVector:      "yashan",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/yasdb_123@127.0.0.1:1688?compat_vector=mysql",
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      false,
				compatVector:      "mysql",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/yasdb_123@127.0.0.1:1688?compat_vector=null",
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      false,
				compatVector:      "null",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/yasdb_123@127.0.0.1:1688?compat_vector=yashan&autocommit=true&number_as_string=true",
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      true,
				numberAsString:    true,
				compatVector:      "yashan",
				dateFormat:        _DefaultDbDateFormat,
				timeFormat:        _DefaultDbTimeFormat,
				timestampFormat:   _DefaultDbTimestampFormat,
				timestampTzFormat: _DefaultDbTimestampTzFormat,
				dsIntervalFormat:  _DefaultDbDsIntervalFormat,
				ymIntervalFormat:  _DefaultDbYmIntervalFormat,
				cliPrepare:        true,
			},
		},
		{
			"sys/yasdb_123@127.0.0.1:1688?compat_vector=yashan&autocommit=true&number_as_string=true&date_format=YYYY-MM-DD&time_format=HH24:MI:SS.FF2&timestamp_format=YYYY-MM-DD HH24:MI:SS.FF9&timestamp_tz_format=YYYY-MM-DD HH12:MI:SS.FF TZH:TZM&ds_interval_format=DD HH12:MI:SS.FF&ym_interval_format=YYYY-MM",
			&DataSourceName{
				User:              "sys",
				Password:          "yasdb_123",
				Url:               "127.0.0.1:1688",
				IsAutoCommit:      true,
				numberAsString:    true,
				compatVector:      "yashan",
				dateFormat:        "YYYY-MM-DD",
				timeFormat:        "HH24:MI:SS.FF2",
				timestampFormat:   "YYYY-MM-DD HH24:MI:SS.FF9",
				timestampTzFormat: "YYYY-MM-DD HH12:MI:SS.FF TZH:TZM",
				dsIntervalFormat:  "DD HH12:MI:SS.FF",
				ymIntervalFormat:  "YYYY-MM",
				cliPrepare:        true,
			},
		},
	}

	for index, dt := range dsnTests {
		fmt.Println(dt.dsnStr)
		dsn, _ := ParseDSN(dt.dsnStr)
		if !reflect.DeepEqual(dsn, dt.expectedDSN) {
			t.Errorf("test case:%d. failed to parse dsn:\n%s  expected \n%+v, actual \n%+v", index, dt.dsnStr, dt.expectedDSN, dsn)
		}
	}
}
